# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: prometheus-config
#   namespace: monitoreo
# data:
#   prometheus.yml: |
#     global:
#       scrape_interval: 5s
#       evaluation_interval: 5s

#     scrape_configs:
#       # Prometheus se auto-scrapea
#       - job_name: 'prometheus'
#         static_configs:
#           - targets: ['prometheus.monitoreo.svc.cluster.local:9090']

#       # <<< ACÃ VA LO DEL PUSHGATEWAY >>>
#       - job_name: 'pushgateway'
#         static_configs:
#           - targets: ['pushgateway.monitoreo.svc.cluster.local:9091']
